### ISSUE TITLE
Controls (Enhancement)

### ISSUE THREAD

**Issue by Thekenbaum** [SonicMastr/Doki-Doki-Literature-Club-Vita#1]
I would like it if I could use the controls on my vita to play the game.
I would prefer not to smudge my screen.

**Comment by SonicMastr** [comment]
This was already touched on (pun intended) and the game itself just doesn't support controller input. Either somebody would need to make a mod or Dan himself would need to update the game's code to support controller. I already technically forced controller input to be used, but there's just nothing to handle it in game.

**Comment by Shad9w** [comment]
You can use ReVita to bind some buttons to screen touches. Makes scrolling through dialog easier.
